MVPSolutions/Controllers/YsowController.cs
using MVPSolutions.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace MVPSolutions.Controllers
{
    public class YsowController : Controller
    {
        // GET: Ysow
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(MailModels e)
        {
            if (ModelState.IsValid)
            {

                //prepare email
                var toAddress = "mvpstorytellingstyling@gmail.com";
                var fromAddress = e.Email.ToString();
                var subject = "Story idea from " + e.Name;
                var message = new StringBuilder();
                message.Append("Name: " + e.Name + "\n");
                message.Append("Name: " + e.Lastname + "\n");
                message.Append("Email: " + e.Email + "\n");
                message.Append(e.Idea);

                //start email Thread
                var tEmail = new Thread(() =>
               SendEmail(toAddress, fromAddress, subject, message.ToString()));
                tEmail.Start();
            }
            return View();
        }

        public void SendEmail(string toAddress, string fromAddress,
                      string subject, string message)
        {
            try
            {
                using (var mail = new MailMessage())
                {
                    const string email = "mvpsolutionsmail@gmail.com";
                    const string password = "1908yP2ul$";

                    var loginInfo = new NetworkCredential(email, password);


                    mail.From = new MailAddress(fromAddress);
                    mail.To.Add(new MailAddress(toAddress));
                    mail.Subject = subject;
                    mail.Body = message;
                    mail.IsBodyHtml = true;

                    try
                    {
                        using (var smtpClient = new SmtpClient("smtp.gmail.com", 587))
                        {
                            smtpClient.EnableSsl = true;
                            smtpClient.UseDefaultCredentials = false;
                            smtpClient.Credentials = loginInfo;
                            smtpClient.Send(mail);
                        }
                    }
                    finally
                    {
                        //dispose the client
                        mail.Dispose();
                    }

                }
            }
            catch (SmtpFailedRecipientsException ex)
            {
                foreach (SmtpFailedRecipientException t in ex.InnerExceptions)
                {
                    var status = t.StatusCode;
                    if (status == SmtpStatusCode.MailboxBusy ||
                        status == SmtpStatusCode.MailboxUnavailable)
                    {
                        Response.Write("Delivery failed - retrying in 5 seconds.");
                        System.Threading.Thread.Sleep(5000);
                        //resend
                        //smtpClient.Send(message);
                    }
                    else
                    {
                        Response.Write("Failed to deliver message to {0}" + t.FailedRecipient);
                    }
                }
            }
            catch (SmtpException Se)
            {
                // handle exception here
                Response.Write(Se.ToString());
            }

            catch (Exception ex)
            {
                Response.Write(ex.ToString());
            }

        }
    }
}

MVPSolutions/Views/Ysow/Index.cshtml
@model MVPSolutions.Models.MailModels
@{
    ViewBag.Title = "Your Story, Our World";
}
<header id="top">
    <div class="text-vertical-top text-main header-stories">
        <h1>Your Story, Our World </h1>
        <h2>Tell me your story & let’s create our world together</h2>
    </div>
</header>
<hr />
<!-- Portfolio -->
<section id="ysow" class="header-stories">
    <div class="text-vertical-center text-main">
        @using (Html.BeginForm("Index", "Ysow", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @id = "contact-form", role = "form" }))
            {
            @Html.ValidationSummary()
            <fieldset>
                <div class="row">
                    <label class="form-item" for="name">*Your name:</label><br />
                    @Html.TextBoxFor(m => m.Name, new { @placeholder = "Name", @type = "text", @size = 30 })
                    <br />
                </div>
                <div class="row">
                    <label class="form-item" for="lastname">*Your lastname:</label><br />
                    @Html.TextBoxFor(m => m.Lastname, new { @placeholder = "Lastname", @type = "text", @size = 30 })
                    <br />
                </div>
                <div class="row">
                    <label class="form-item" for="email">*Your email:</label><br />
                    @Html.TextBoxFor(m => m.Email, new { @placeholder = "Email Address", @type = "email", @size = 30 })
                    <br />
                </div>
                <div class="row">
                    <label class="form-item" for="idea">*Your idea:</label><br />
                    @Html.TextAreaFor(m => m.Idea, new { @placeholder = "Idea", @cols = 30, @rows = 9 })
                    <br />
                </div>
                <div class="button-wrapper">
                    <input type="submit" value="Send" name="submit" class="button" />
                </div>
            </fieldset>
                <br />
                <p class="small">* are required fields.</p>
        }
    </div>
    <!-- /.container -->
</section>